version: '3.5'

services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - 80:80
        links:
            - 'php'
            - 'mysql'
        volumes:
            - '../:/var/www/task1'
            - './nginx:/etc/nginx/conf.d'

    php:
        container_name: php
        expose:
            - 9000
        build:
            dockerfile: php-dockerfile
            context: .
        volumes:
            - '../:/var/www/task1'
            - './php.ini:/usr/local/etc/php/conf.d/php.ini'

    mysql:
        container_name: mysql
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3307:3306'
        volumes:
            - './mysqldata:/var/lib/mysql'
